[tox]
envlist = py{310,314}, coverage, style, typecheck, readme

[testenv]
setenv =
    COVERAGE_FILE={toxworkdir}/.coverage.{envname}
    PYTHONPYCACHEPREFIX={toxworkdir}/.pycache
usedevelop = True
dependency_groups = test
commands = pytest {posargs:-vv --cov=snip_stitch tests}

[testenv:coverage]
setenv = COVERAGE_FILE={toxworkdir}/.coverage
skip_install = True
deps = coverage
commands = coverage combine
           coverage report -m
           coverage xml
           coverage html

[testenv:style]
skip_install = True
deps = ruff
commands = ruff check
           ruff format --diff

[testenv:typecheck]
usedevelop = True
deps = pyright
commands = pyright

[testenv:readme]
skip_install = True
deps = uv
       twine
commands = uv build -q -o {envdir}/dist
           twine check {envdir}/dist/*

[testenv:reformat]
skip_install = True
deps = ruff
commands = ruff check --fix
           ruff format
